name: Bug report
description: Report a problem in convert_object
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: "Thanks for taking the time to file a bug report."
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Include a minimal repro if possible.
      placeholder: |
        1. ...
        2. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: input
    id: package-version
    attributes:
      label: Package version
      description: Output of `dart pub deps --style=list | rg convert_object` or your pubspec.
    validations:
      required: true
  - type: input
    id: dart-version
    attributes:
      label: Dart SDK version
      description: Output of `dart --version`.
    validations:
      required: true
  - type: input
    id: platform
    attributes:
      label: OS / Platform
      description: e.g. macOS 14, Ubuntu 22.04, Windows 11.
